import { CalendarEvent, GoogleTask, GoogleTaskList, InstructorProfile } from "./types";

export const mockCalendars = [
          {
            id: "mock-primary",
            summary: "Calendario Principal (Pronautic)",
            primary: true,
            backgroundColor: "#4f46e5",
          },
          {
            id: "mock-sec",
            summary: "Exámenes Oficiales DGMM / Junta",
            primary: false,
            backgroundColor: "#06b6d4",
          },
          {
            id: "mock-stcw",
            summary: "Cursos STCW",
            primary: false,
            backgroundColor: "#e04f34",
          },
          {
            id: "mock-ism",
            summary: "Pendientes ISM",
            primary: false,
            backgroundColor: "#0ea5e9",
          },
        ];

export const mockEventsList: CalendarEvent[] = [
          {
            id: "evt-01",
            summary:
              "Curso Patrón de Embarcaciones de Recreo (PER) - Prácticas de Navegación",
            description:
              "Prácticas de seguridad y navegación oficiales de la DGMM para PER. Navegación costera y maniobras de atraque.",
            location: "Velero Escuela 'Capitán Pronautic'",
            start: { dateTime: event1Start.toISOString() },
            end: { dateTime: event1End.toISOString() },
            calendarId: "mock-primary",
            calendarName: "Calendario Principal (Pronautic)",
          },
          {
            id: "evt-02",
            summary: "Curso de Formación Básica en Seguridad STCW (DGMM)",
            description:
              "Módulo certificado obligatorio para tripulación profesional. Prácticas en simulador de comunicaciones náuticas.",
            location: "Aula de Simulación Práctica",
            start: { dateTime: event2Start.toISOString() },
            end: { dateTime: event2End.toISOString() },
            calendarId: "mock-primary",
            calendarName: "Calendario Principal (Pronautic)",
          },
          {
            id: "evt-03",
            summary: "Examen Práctico Oficial de Radio GMDSS",
            description:
              "Examen final del módulo de comunicaciones de largo alcance para Patrón de Yate.",
            location: "Simulador de Radio GMDSS",
            start: { dateTime: event3Start.toISOString() },
            end: { dateTime: event3End.toISOString() },
            calendarId: "mock-sec",
            calendarName: "Exámenes Oficiales DGMM / Junta",
          },
          {
            id: "evt-stcw-june-fb",
            summary: "Curso de Formación Básica en Seguridad STCW (DGMM)",
            description:
              "Módulo certificado oficial obligatorio para tripulación profesional marítima. Supervivencia en el mar y lucha contra incendios.",
            location: "Aula de Simulación Práctica",
            start: { dateTime: "2026-06-15T09:00:00" },
            end: { dateTime: "2026-06-19T14:00:00" },
            calendarId: "mock-stcw",
            calendarName: "Cursos STCW",
          },
          {
            id: "evt-stcw-june-gmdss",
            summary: "Curso de Operador de Radio GMDSS STCW",
            description:
              "Formación de seguridad en radiocomunicaciones de socorro y correspondencia pública para la marina mercante.",
            location: "Simulador de Radio GMDSS",
            start: { dateTime: "2026-06-22T16:00:00" },
            end: { dateTime: "2026-06-26T20:30:00" },
            calendarId: "mock-stcw",
            calendarName: "Cursos STCW",
          },
          {
            id: "evt-ism-june-audit",
            summary: "Auditoría Interna ISM y Coordinación de Emergencia",
            description:
              "Inspección reglamentaria del Sistema de Gestión de la Seguridad (Cód. ISM) para buques de la escuela. Simulacro de hombre al agua y abandono.",
            location: "Aula Náutica B",
            start: { dateTime: "2026-06-29T09:00:00" },
            end: { dateTime: "2026-06-29T18:00:00" },
            calendarId: "mock-ism",
            calendarName: "Pendientes ISM",
          },
        ];

export const mockLists: GoogleTaskList[] = [
          { id: "lst-01", title: "Auditoría de Calidad Pronautic" },
          { id: "lst-02", title: "Mantenimiento General Flota" },
        ];

export const mockTasksList: GoogleTask[] = [
          {
            id: "t1",
            title: "Control de estanqueidad y escotillas velero",
            status: "needsAction",
            listId: "lst-01",
            listTitle: "Auditoría de Calidad Pronautic",
          },
          {
            id: "t2",
            title: "Verificar extintores y trajes de supervivencia",
            status: "completed",
            listId: "lst-01",
            listTitle: "Auditoría de Calidad Pronautic",
          },
          {
            id: "t3",
            title: "Archivar firmas oficiales de asistencia PER",
            status: "needsAction",
            listId: "lst-01",
            listTitle: "Auditoría de Calidad Pronautic",
          },
          {
            id: "t4",
            title: "Firmar actas oficiales y actas de examen",
            status: "needsAction",
            listId: "lst-01",
            listTitle: "Auditoría de Calidad Pronautic",
          },
          {
            id: "t5",
            title: "Limpiar y desinfectar puestos en simulador de radio",
            status: "needsAction",
            listId: "lst-01",
            listTitle: "Auditoría de Calidad Pronautic",
          },
          {
            id: "t6",
            title: "Revisar anclas y cabos de fondeo",
            status: "needsAction",
            listId: "lst-02",
            listTitle: "Mantenimiento General Flota",
          },
        ];

export const DEFAULT_AULAS = [
  "Aula Teórica del Puerto",
  "Aula de Simulación Práctica",
  "Aula Náutica B",
  "Simulador de Radio GMDSS",
];

export const DEFAULT_EMBARCACIONES = [
  "Velero Escuela 'Capitán Pronautic'",
  "Lancha Motora 'MiniPronautic'",
  "Yate de Prácticas 'Alborán'",
  "Semirrígida de Apoyo 'Pronautic Dos'",
];

export const DEFAULT_STAFF: InstructorProfile[] = [
  {
    id: "s1",
    branca: "STCW",
    name: "Abel Aguilar",
    category: "Capitán",
    phone: "630 184 142",
    email: "abel_aguilar@hotmail.es",
    location: "",
  },
  {
    id: "s2",
    branca: "ESBARJO",
    name: "Adrià Onsés",
    category: "",
    phone: "663 37 60 30",
    email: "adriaonsessoler@gmail.com",
    location: "",
  },
  {
    id: "s3",
    branca: "ESBARJO",
    name: "Aina Bauzà",
    category: "",
    phone: "617 95 06 87",
    email: "",
    location: "",
  },
  {
    id: "s4",
    branca: "SANITARI",
    name: "Ainhoa Ruiz Segarra",
    category: "Enfermera",
    phone: "677 742 731",
    email: "ainhoaruiz10@gmail.com",
    location: "St Joan Despi",
  },
  {
    id: "s5",
    branca: "STCW",
    name: "Albert Pons",
    category: "Capitán",
    phone: "626 459 261",
    email: "pons640@gmail.com",
    location: "Olesa de Montserrat",
  },
  {
    id: "s6",
    branca: "STCW",
    name: "Albert Rondon",
    category: "1ª Piloto",
    phone: "603 217 894",
    email: "albertondon22@gmail.com",
    location: "Brazil",
  },
  {
    id: "s7",
    branca: "STCW",
    name: "Albert Serra",
    category: "1ª Piloto",
    phone: "650 985 753",
    email: "alserpe@hotmail.com",
    location: "",
  },
  {
    id: "s8",
    branca: "STCW",
    name: "Alejandro Ramírez Sánchez",
    category: "Máquinas",
    phone: "661 316 582",
    email: "alejandro02061974@gmail.com",
    location: "Cádiz-Algeciras",
  },
  {
    id: "s9",
    branca: "SANITARI",
    name: "Alfredo Trevisan Sanchez",
    category: "Enfermero",
    phone: "678 470 222",
    email: "alfredots@hotmail.com",
    location: "Castelldefels",
  },
  {
    id: "s10",
    branca: "STCW",
    name: "Alicia Gonzalez Diez",
    category: "Enfermera",
    phone: "679 431 520",
    email: "aligonzalezdiez@gmail.com",
    location: "",
  },
  {
    id: "s11",
    branca: "SANITARI",
    name: "Andrea Alvarez Serén",
    category: "Enfermera",
    phone: "680 929 492",
    email: "andreaalser@gmail.com",
    location: "Sta Coloma de Gramanet",
  },
  {
    id: "s12",
    branca: "STCW",
    name: "Benjamin Garcia",
    category: "Enfermero",
    phone: "602 094 938",
    email: "raimigarcia@gmail.com",
    location: "BCN",
  },
  {
    id: "s13",
    branca: "STCW",
    name: "Bernat Valverde",
    category: "Capitán",
    phone: "616 643 845",
    email: "bernat.valverde@gmail.com",
    location: "",
  },
  {
    id: "s14",
    branca: "STCW",
    name: "Conrad Guerra",
    category: "1ª Piloto",
    phone: "647 760 175",
    email: "conradguerra22@gmail.com",
    location: "Barcelona",
  },
  {
    id: "s15",
    branca: "ESBARJO",
    name: "Dani Cianfagna",
    category: "",
    phone: "686689285",
    email: "danielcapria@gmail.com",
    location: "",
  },
  {
    id: "s16",
    branca: "ESBARJO",
    name: "Dani Company",
    category: "",
    phone: "605 50 37 47",
    email: "",
    location: "",
  },
  {
    id: "s17",
    branca: "ESBARJO",
    name: "Dani Monzón",
    category: "",
    phone: "648706255",
    email: "danielmonzon.dmr@gmail.com",
    location: "",
  },
  {
    id: "s18",
    branca: "ESBARJO",
    name: "Dani Zamora",
    category: "",
    phone: "666 252 065",
    email: "dani.zamora30@gmail.com",
    location: "",
  },
  {
    id: "s19",
    branca: "STCW",
    name: "Daniel Company",
    category: "Capitán",
    phone: "605 503 747",
    email: "daniel_company@hotmail.com",
    location: "Tarragona",
  },
  {
    id: "s20",
    branca: "STCW",
    name: "Daniel Monzón",
    category: "Capitán",
    phone: "648 706 255",
    email: "danielmonzon.dmr@gmail.com",
    location: "Barcelona",
  },
  {
    id: "s21",
    branca: "STCW",
    name: "David Llinero",
    category: "",
    phone: "",
    email: "",
    location: "",
  },
  {
    id: "s22",
    branca: "ESBARJO",
    name: "David Navarro",
    category: "",
    phone: "694281727",
    email: "dnmbcn@icloud.com",
    location: "",
  },
  {
    id: "s23",
    branca: "SANITARI",
    name: "Deborah Blasco Muda",
    category: "Enfermera",
    phone: "658 504 714",
    email: "dblasco.muda@gmail.com",
    location: "Vilassar",
  },
  {
    id: "s24",
    branca: "ESBARJO",
    name: "Georgina Castro Fresno",
    category: "Enfermera",
    phone: "639 459 680",
    email: "georginacf98@gmail.com",
    location: "Barcelona",
  },
  {
    id: "s25",
    branca: "STCW",
    name: "Guillermo Gil",
    category: "1ª Piloto",
    phone: "656 659 442",
    email: "guillermogil24@hotmail.com",
    location: "Zaragoza",
  },
  {
    id: "s26",
    branca: "SANITARI",
    name: "Ignasi Bernaus",
    category: "Enfermero",
    phone: "633 025 363",
    email: "ignasi.bernaus@gmail.com",
    location: "BCN",
  },
  {
    id: "s27",
    branca: "STCW",
    name: "Imad",
    category: "",
    phone: "669 53 27 28",
    email: "elimaad@hotmail.com",
    location: "",
  },
  {
    id: "s28",
    branca: "STCW",
    name: "Joan Rius",
    category: "Capitán",
    phone: "696 133 532",
    email: "riusisrael@hotmail.com",
    location: "Calafell",
  },
  {
    id: "s29",
    branca: "STCW",
    name: "Mehdi Aberhouche",
    category: "",
    phone: "747 402 296",
    email: "mehdiaberhouche@gmail.com",
    location: "",
  },
  {
    id: "s30",
    branca: "SANITARI",
    name: "Maria Pardo",
    category: "Doctora",
    phone: "610 242 969",
    email: "mariapardosd@gmail.com",
    location: "BCN",
  },
  {
    id: "s31",
    branca: "ESBARJO",
    name: "Quim Hervas",
    category: "",
    phone: "617 888 888",
    email: "quim.hervas@gmail.com",
    location: "",
  },
];

export const PRONAUTIC_COURSES_CATALOG = [
  {
    id: "stcw-fb",
    name: "Formación Básica en Seguridad STCW",
    code: "STCW-FB",
  },
  {
    id: "stcw-gmdss",
    name: "Operador de Radio GMDSS STCW",
    code: "STCW-GMDSS",
  },
  {
    id: "per-motor",
    name: "Patrón de Embarcaciones de Recreo (PER)",
    code: "PER-MOTOR",
  },
  { id: "per-vela", name: "Habilitación a Vela (PER Vela)", code: "PER-VELA" },
  { id: "pnb", name: "Patrón de Navegación Básica (PNB)", code: "PNB" },
  { id: "ln", name: "Licencia de Navegación (Titulín)", code: "LN" },
  { id: "py", name: "Patrón de Yate (PY)", code: "PY" },
  { id: "cy", name: "Capitán de Yate (CY)", code: "CY" },
];

